"""Run a strategy end-to-end with data generated by this repository.

The example deliberately has no external market-data dependency.  It creates
one synthetic futures data set, reads it through the public Readers, converts
it into a TimeSlice stream, and runs a small SMA-cross strategy in the normal
BacktestEngine runtime.

Run from the repository root::

    python -m example.synthetic_sma_cross_backtest

Generated xlsx inputs and csv outputs are stored below ``example/data`` and
are ignored by Git.
"""

from __future__ import annotations

import sys
from collections import deque
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

import pandas as pd

from autotrade.backtest import BacktestEngine
from autotrade.backtest.data import (
    DataManager,
    DataRoutingConfig,
    FutureStateReader,
    TradeBarReader,
)
from autotrade.coreutils.constant import Direction, Exchange, Interval, OrderStatus, OrderType
from autotrade.coreutils.object import OrderData, OrderRequest, PositionData, TradeData
from autotrade.strategy.strategy_base import StrategyBase
from example.generate_synthetic_data import SyntheticDataConfig, write_synthetic_dataset


class SyntheticSmaCrossStrategy(StrategyBase):
    """A minimal StrategyBase implementation using one named Bar source."""

    def __init__(
        self,
        event_engine,
        security_manager,
        *,
        instrument_id: str,
        data_name: str = "future_1m",
        short_window: int = 5,
        long_window: int = 15,
    ) -> None:
        super().__init__(event_engine, security_manager)
        if short_window <= 0 or short_window >= long_window:
            raise ValueError("require 0 < short_window < long_window")
        self.instrument_id = instrument_id
        self.data_name = data_name
        self.short_window = short_window
        self.long_window = long_window
        self.closes: deque[float] = deque(maxlen=long_window)
        self.net_position = 0.0
        self.pending = False

    def on_data(self, slice_) -> None:
        # Input layer: only consume the explicitly named Bar stream.
        bar = slice_.get_bar(self.instrument_id, data_name=self.data_name)
        if bar is None:
            return

        # Decision layer: keep strategy-private indicator state.
        self.closes.append(float(bar.close))
        if len(self.closes) < self.long_window or self.pending:
            return
        short_sma = sum(list(self.closes)[-self.short_window :]) / self.short_window
        long_sma = sum(self.closes) / self.long_window

        # Target layer: this example targets exactly one long or one short lot.
        desired_position = 1.0 if short_sma >= long_sma else -1.0
        if desired_position == self.net_position:
            return

        # Request submission layer: emit only the position delta.
        delta = desired_position - self.net_position
        self.pending = True
        self.push_order_request(
            OrderRequest(
                instrument_id=self.instrument_id,
                exchange=bar.exchange or Exchange.CFFEX,
                direction=Direction.LONG if delta > 0 else Direction.SHORT,
                type=OrderType.MARKET,
                volume=abs(delta),
                reference="synthetic_sma_cross",
            )
        )

    def on_order(self, order: OrderData) -> None:
        if order.instrument_id != self.instrument_id:
            return
        if order.status in {OrderStatus.ALLCANCELLED, OrderStatus.REJECTED}:
            self.pending = False

    def on_trade(self, trade: TradeData) -> None:
        if trade.instrument_id == self.instrument_id:
            self.pending = False

    def on_position(self, position: PositionData) -> None:
        # Feedback layer: OMS publishes the authoritative net position.
        if position.instrument_id == self.instrument_id:
            self.net_position = float(position.volume)


def build_data_manager(files: dict[str, Path]) -> DataManager:
    """Read generated xlsx files and route them into a backtest TimeSlice stream."""

    manager = DataManager(
        DataRoutingConfig(
            strategy_data_names={"future_1m"},
            security_data_names={"future_states", "future_1m"},
            valuation_data_names={"future_1m"},
        )
    )
    manager.add_data(
        "future_states",
        FutureStateReader().read(
            pd.read_excel(files["future_instruments"]),
            exchange=Exchange.CFFEX,
        ),
    )
    manager.add_data(
        "future_1m",
        TradeBarReader().read(
            pd.read_excel(files["future_bars"]),
            interval=Interval.K_1M,
            exchange=Exchange.CFFEX,
        ),
    )
    return manager


def main() -> None:
    output_dir = PROJECT_ROOT / "example" / "data" / "synthetic_sma_cross"
    files = write_synthetic_dataset(
        SyntheticDataConfig(
            kind="futures",
            frequency="1m",
            periods=480,
            num_futures=1,
            seed=17,
        ),
        output_dir,
    )
    manager = build_data_manager(files)

    engine = BacktestEngine(initial_cash=100_000)
    strategy = SyntheticSmaCrossStrategy(
        engine.event_engine,
        engine.security_manager,
        instrument_id="SYNF001",
    )
    strategy.initialize()
    result = engine.run(manager.stream())
    strategy.stop()

    engine.get_trade_log_df().to_csv(output_dir / "trades.csv", index=False)
    engine.get_account_daily_df().to_csv(output_dir / "account_daily.csv")
    print(f"generated inputs: {output_dir}")
    print(f"processed TimeSlices: {engine.processed_slice_count}")
    print(f"confirmed trades: {len(engine.get_trade_log_df())}")
    print(f"total return: {result['total_return']}")


if __name__ == "__main__":
    main()
