# coding=utf-8
class FeeType(object):
    fee_by_amt = 0
    fee_by_val = 1


class SlipType(object):
    slip_by_pct = 0
    slip_by_point = 1


# 合约交易信息
Contract_info = {'A': dict(margin_rate=0.12, contract_amt=10.0,
                           fee_type=FeeType.fee_by_amt, fee_unit=2.0,
                           slip_type=SlipType.slip_by_point, slip_unit=1.0,
                           limit_change=0.08,
                           exchange='DCE',
                           name='黄大豆1号'),

                 'AG': dict(margin_rate=0.12, contract_amt=15.0,
                            fee_type=FeeType.fee_by_val, fee_unit=5e-05,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.1,
                            exchange='SHFE',
                            name='白银'),

                 'AL': dict(margin_rate=0.10, contract_amt=5.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=3,
                            slip_type=SlipType.slip_by_point, slip_unit=5.0,
                            limit_change=0.07,
                            exchange='SHFE',
                            name='铝'),

                 'AO': dict(margin_rate=0.09, contract_amt=20.0,
                            fee_type=FeeType.fee_by_val, fee_unit=0.0001,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.07,
                            exchange='SHFE',
                            name='氧化铝'),

                 'AP': dict(margin_rate=0.08, contract_amt=10.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=20,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.09,
                            exchange='ZCE',
                            name='鲜苹果'),

                 'AU': dict(margin_rate=0.12, contract_amt=1000.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=10,
                            slip_type=SlipType.slip_by_point, slip_unit=0.02,
                            limit_change=0.08,
                            exchange='SHFE',
                            name='黄金'),

                 'B': dict(margin_rate=0.07, contract_amt=10.0,
                           fee_type=FeeType.fee_by_amt, fee_unit=2,
                           slip_type=SlipType.slip_by_point, slip_unit=1.0,
                           limit_change=0.08,
                           exchange='DCE',
                           name='黄大豆2号'),

                 'BB': dict(margin_rate=0.20, contract_amt=500.0,
                            fee_type=FeeType.fee_by_val, fee_unit=1e-04,
                            slip_type=SlipType.slip_by_point, slip_unit=0.05,
                            limit_change=0.1,
                            exchange='DCE', ),

                 'BC': dict(margin_rate=0.09, contract_amt=5.0,
                            fee_type=FeeType.fee_by_val, fee_unit=1e-05,
                            slip_type=SlipType.slip_by_point, slip_unit=10.0,
                            limit_change=0.07,
                            exchange='INE',
                            name='国际铜'),

                 'BR': dict(margin_rate=0.09, contract_amt=5.0,
                            fee_type=FeeType.fee_by_val, fee_unit=2e-05,
                            slip_type=SlipType.slip_by_point, slip_unit=5.0,
                            limit_change=0.07,
                            exchange='SHFE',
                            name='丁二烯橡胶'),

                 'BU': dict(margin_rate=0.10, contract_amt=10.0,
                            fee_type=FeeType.fee_by_val, fee_unit=1e-04,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.08,
                            exchange='SHFE',
                            name='石油沥青'),

                 'C': dict(margin_rate=0.11, contract_amt=10.0,
                           fee_type=FeeType.fee_by_amt, fee_unit=1.2,
                           slip_type=SlipType.slip_by_point, slip_unit=1.0,
                           limit_change=0.08,
                           exchange='DCE',
                           name='玉米'),

                 'CF': dict(margin_rate=0.07, contract_amt=5.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=4.3,
                            slip_type=SlipType.slip_by_point, slip_unit=5.0,
                            limit_change=0.06,
                            exchange='ZCE',
                            name='棉花'),

                 'CJ': dict(margin_rate=0.07, contract_amt=5.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=3.0,
                            slip_type=SlipType.slip_by_point, slip_unit=5.0,
                            limit_change=0.10,
                            exchange='ZCE',
                            name='干制红枣'),

                 'CS': dict(margin_rate=0.07, contract_amt=10.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=1.5,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.07,
                            exchange='DCE',
                            name='玉米淀粉'),

                 'CU': dict(margin_rate=0.10, contract_amt=5.0,
                            fee_type=FeeType.fee_by_val, fee_unit=5e-05,
                            slip_type=SlipType.slip_by_point, slip_unit=10.0,
                            limit_change=0.07,
                            exchange='SHFE',
                            name='阴极铜'),

                 'CY': dict(margin_rate=0.05, contract_amt=5.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=4.0,
                            slip_type=SlipType.slip_by_point, slip_unit=5.0,
                            limit_change=0.08,
                            exchange='ZCE',
                            name='棉纱'),

                 'EB': dict(margin_rate=0.12, contract_amt=5.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=3.0,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.07,
                            exchange='DCE',
                            name='苯乙烯'),

                 'EC': dict(margin_rate=0.18, contract_amt=50.0,
                            fee_type=FeeType.fee_by_val, fee_unit=6e-4,
                            slip_type=SlipType.slip_by_point, slip_unit=0.1,
                            limit_change=0.16,
                            exchange='INE',
                            name='集运指数（欧线）期货'),

                 'EG': dict(margin_rate=0.11, contract_amt=10.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=4.0,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.07,
                            exchange='DCE',
                            name='乙二醇'),

                 'FB': dict(margin_rate=0.2, contract_amt=500.0,
                            fee_type=FeeType.fee_by_val, fee_unit=1e-04,
                            slip_type=SlipType.slip_by_point, slip_unit=0.05),

                 'FG': dict(margin_rate=0.07, contract_amt=20.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=3,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.08,
                            exchange='ZCE',
                            name='平板玻璃'),

                 'FU': dict(margin_rate=0.10, contract_amt=10.0,
                            fee_type=FeeType.fee_by_val, fee_unit=5e-05,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.08,
                            exchange='SHFE',
                            name='燃料油'),

                 'HC': dict(margin_rate=0.10, contract_amt=10.0,
                            fee_type=FeeType.fee_by_val, fee_unit=1e-04,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.05,
                            exchange='SHFE',
                            name='热轧卷板'),

                 'I': dict(margin_rate=0.12, contract_amt=100.0,
                           fee_type=FeeType.fee_by_val, fee_unit=12e-05,
                           slip_type=SlipType.slip_by_point, slip_unit=0.5,
                           limit_change=0.11,
                           exchange='DCE',
                           name='铁矿石'),

                 'J': dict(margin_rate=0.15, contract_amt=100.0,
                           fee_type=FeeType.fee_by_val, fee_unit=6e-05,
                           slip_type=SlipType.slip_by_point, slip_unit=0.5,
                           limit_change=0.08,
                           exchange='DCE',
                           name='焦炭'),

                 'JD': dict(margin_rate=0.09, contract_amt=10.0,
                            fee_type=FeeType.fee_by_val, fee_unit=15e-05,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.08,
                            exchange='DCE',
                            name='鲜鸡蛋'),

                 'JM': dict(margin_rate=0.15, contract_amt=60.0,
                            fee_type=FeeType.fee_by_val, fee_unit=6e-05,
                            slip_type=SlipType.slip_by_point, slip_unit=0.5,
                            limit_change=0.08,
                            exchange='DCE',
                            name='焦煤'),

                 'JR': dict(margin_rate=0.05, contract_amt=20.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=3,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            name='粳稻谷'),

                 'L': dict(margin_rate=0.10, contract_amt=5.0,
                           fee_type=FeeType.fee_by_amt, fee_unit=2,
                           slip_type=SlipType.slip_by_point, slip_unit=1.0,
                           limit_change=0.06,
                           exchange='DCE',
                           name='线型低密度聚乙烯'),

                 'LC': dict(margin_rate=0.09, contract_amt=1.0,
                            fee_type=FeeType.fee_by_val, fee_unit=0.00008,
                            slip_type=SlipType.slip_by_point, slip_unit=50.0,
                            limit_change=0.10,
                            exchange='GFEX',
                            name='碳酸锂'),

                 'LH': dict(margin_rate=0.15, contract_amt=16.0,
                            fee_type=FeeType.fee_by_val, fee_unit=3e-04,
                            slip_type=SlipType.slip_by_point, slip_unit=5.0,
                            limit_change=0.06,
                            exchange='DCE',
                            name='生猪'),

                 'LU': dict(margin_rate=0.10, contract_amt=10.0,
                            fee_type=FeeType.fee_by_val, fee_unit=1e-05,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.08,
                            exchange='INE',
                            name='低硫燃料油'),

                 'LR': dict(margin_rate=0.05, contract_amt=20.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=3,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            name='晚籼稻'),

                 'M': dict(margin_rate=0.08, contract_amt=10.0,
                           fee_type=FeeType.fee_by_amt, fee_unit=2.5,
                           slip_type=SlipType.slip_by_point, slip_unit=1.0,
                           limit_change=0.06,
                           exchange='DCE',
                           name='豆粕'),

                 'MA': dict(margin_rate=0.08, contract_amt=10.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=2,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.07,
                            exchange='ZCE',
                            name='甲醇'),

                 'NI': dict(margin_rate=0.10, contract_amt=1.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=6,
                            slip_type=SlipType.slip_by_point, slip_unit=10,
                            limit_change=0.10,
                            exchange='SHFE',
                            name='镍'),

                 'NR': dict(margin_rate=0.10, contract_amt=10.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=6,
                            slip_type=SlipType.slip_by_pct, slip_unit=5,
                            limit_change=0.08,
                            exchange='INE', name='20号胶'),

                 'OI': dict(margin_rate=0.08, contract_amt=10.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=2,
                            slip_type=SlipType.slip_by_point, slip_unit=1,
                            limit_change=0.06,
                            exchange='ZCE',
                            name='菜籽油'),

                 'P': dict(margin_rate=0.10, contract_amt=10.0,
                           fee_type=FeeType.fee_by_amt, fee_unit=2.5,
                           slip_type=SlipType.slip_by_point, slip_unit=2.0,
                           limit_change=0.07,
                           exchange='DCE',
                           name='棕榈油'),

                 'PB': dict(margin_rate=0.10, contract_amt=5.0,
                            fee_type=FeeType.fee_by_val, fee_unit=4e-05,
                            slip_type=SlipType.slip_by_point, slip_unit=5.0,
                            limit_change=0.07,
                            exchange='SHFE',
                            name='铅'),

                 'PF': dict(margin_rate=0.08, contract_amt=5.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=3.0,
                            slip_type=SlipType.slip_by_point, slip_unit=2.0,
                            limit_change=0.07,
                            exchange='ZCE',
                            name='涤纶短纤'),

                 'PG': dict(margin_rate=0.11, contract_amt=20.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=6.0,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.07,
                            exchange='DCE',
                            name='液化石油气'),

                 'PK': dict(margin_rate=0.07, contract_amt=5.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=4.0,
                            slip_type=SlipType.slip_by_point, slip_unit=2.0,
                            limit_change=0.07,
                            exchange='ZCE',
                            name='花生仁'),

                 'PM': dict(margin_rate=0.05, contract_amt=50.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=5.0,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            name='普通小麦'),

                 'PP': dict(margin_rate=0.06, contract_amt=5.0,
                            fee_type=FeeType.fee_by_val, fee_unit=6e-05,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.06,
                            exchange='DCE',
                            name='聚丙烯'),

                 'PR': dict(margin_rate=0.07, contract_amt=15.0,
                            fee_type=FeeType.fee_by_val, fee_unit=5e-05,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.07,
                            exchange='ZCE',
                            name='瓶片'),

                 'PS': dict(margin_rate=0.09, contract_amt=3.0,
                            fee_type=FeeType.fee_by_val, fee_unit=1e-04,
                            slip_type=SlipType.slip_by_point, slip_unit=5.0,
                            limit_change=0.07,
                            exchange='GFEX',
                            name='多晶硅'),

                 'RB': dict(margin_rate=0.05, contract_amt=10.0,
                            fee_type=FeeType.fee_by_val, fee_unit=1e-04,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.05,
                            exchange='SHFE',
                            name='螺纹钢'),

                 'RI': dict(margin_rate=0.20, contract_amt=20.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=2.5,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            name='早籼稻'),

                 'RM': dict(margin_rate=0.08, contract_amt=10.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=1.5,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.06,
                            exchange='ZCE',
                            name='菜籽粕'),

                 'RR': dict(margin_rate=0.06, contract_amt=10.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=1.0,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0),

                 'RS': dict(margin_rate=0.2, contract_amt=10.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=2.0,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            exchange='ZCE',
                            name='油菜籽'
                            ),

                 'RU': dict(margin_rate=0.10, contract_amt=10.0,
                            fee_type=FeeType.fee_by_val, fee_unit=45e-6,
                            slip_type=SlipType.slip_by_point, slip_unit=5.0,
                            limit_change=0.06,
                            exchange='SHFE',
                            name='天然橡胶'),

                 'SA': dict(margin_rate=0.07, contract_amt=20.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=3.5,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.10,
                            exchange='ZCE',
                            name='纯碱'),

                 'SC': dict(margin_rate=0.07, contract_amt=1000.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=20.0,
                            slip_type=SlipType.slip_by_point, slip_unit=0.1,
                            limit_change=0.13,
                            exchange='INE',
                            name='中质含硫原油'),

                 'SF': dict(margin_rate=0.07, contract_amt=5.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=3.0,
                            slip_type=SlipType.slip_by_point, slip_unit=2.0,
                            limit_change=0.08,
                            exchange='ZCE',
                            name='硅铁'),

                 'SH': dict(margin_rate=0.08, contract_amt=30.0,
                            fee_type=FeeType.fee_by_val, fee_unit=1e-4,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.07,
                            exchange='ZCE',
                            name='烧碱'),


                 'SI': dict(margin_rate=0.09, contract_amt=5.0,
                            fee_type=FeeType.fee_by_val, fee_unit=0.0001,
                            slip_type=SlipType.slip_by_point, slip_unit=5.0,
                            limit_change=0.07,
                            exchange='GFEX',
                            name='工业硅'),

                 'SM': dict(margin_rate=0.07, contract_amt=5.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=3.0,
                            slip_type=SlipType.slip_by_point, slip_unit=2.0,
                            limit_change=0.08,
                            exchange='ZCE',
                            name='锰硅'),

                 'SN': dict(margin_rate=0.07, contract_amt=1.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=3.0,
                            slip_type=SlipType.slip_by_point, slip_unit=10,
                            limit_change=0.10,
                            exchange='SHFE',
                            name='锡'),

                 'SP': dict(margin_rate=0.07, contract_amt=10.0,
                            fee_type=FeeType.fee_by_val, fee_unit=0.5e-4,
                            slip_type=SlipType.slip_by_point, slip_unit=2,
                            limit_change=0.06,
                            exchange='SHFE',
                            name='漂白硫酸盐针叶木浆'),

                 'SR': dict(margin_rate=0.07, contract_amt=10.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=3.0,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.06,
                            exchange='ZCE',
                            name='白砂糖'),

                 'SS': dict(margin_rate=0.10, contract_amt=5.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=2.0,
                            slip_type=SlipType.slip_by_point, slip_unit=5.0,
                            limit_change=0.05,
                            exchange='SHFE',
                            name='不锈钢'),

                 'TA': dict(margin_rate=0.07, contract_amt=5.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=3.0,
                            slip_type=SlipType.slip_by_point, slip_unit=2.0,
                            limit_change=0.06,
                            exchange='ZCE',
                            name='精对苯二甲酸（PTA）'),

                 'UR': dict(margin_rate=0.07, contract_amt=20.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=10.0,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            limit_change=0.07,
                            exchange='ZCE',
                            name='尿素'),

                 'V': dict(margin_rate=0.10, contract_amt=5.0,
                           fee_type=FeeType.fee_by_amt, fee_unit=2,
                           slip_type=SlipType.slip_by_point, slip_unit=5.0,
                           limit_change=0.06,
                           exchange='DCE',
                           name='聚氯乙烯'),

                 'WH': dict(margin_rate=0.2, contract_amt=20.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=2.5,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0,
                            name='优质强筋小麦'),

                 'WR': dict(margin_rate=0.2, contract_amt=10.0,
                            fee_type=FeeType.fee_by_val, fee_unit=4e-05,
                            slip_type=SlipType.slip_by_point, slip_unit=1.0),

                 'Y': dict(margin_rate=0.08, contract_amt=10.0,
                           fee_type=FeeType.fee_by_amt, fee_unit=2.5,
                           slip_type=SlipType.slip_by_point, slip_unit=2.0,
                           limit_change=0.06,
                           exchange='DCE',
                           name='豆油'),

                 'ZC': dict(margin_rate=0.12, contract_amt=100.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=4,
                            slip_type=SlipType.slip_by_point, slip_unit=0.2,
                            name='动力煤'),

                 'ZN': dict(margin_rate=0.10, contract_amt=5.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=3,
                            slip_type=SlipType.slip_by_point, slip_unit=5.0,
                            limit_change=0.07,
                            exchange='SHFE',
                            name='锌'),

                 'IC': dict(margin_rate=0.3, contract_amt=200.0,
                            fee_type=FeeType.fee_by_val, fee_unit=23e-06,
                            slip_type=SlipType.slip_by_point, slip_unit=0.2,
                            limit_change=0.10,
                            exchange='CFFEX',
                            name='中证500股指期货'),

                 'IF': dict(margin_rate=0.15, contract_amt=300.0,
                            fee_type=FeeType.fee_by_val, fee_unit=23e-06,
                            slip_type=SlipType.slip_by_point, slip_unit=0.2,
                            limit_change=0.10,
                            exchange='CFFEX',
                            name='沪深300股指期货'),

                 'IH': dict(margin_rate=0.15, contract_amt=300.0,
                            fee_type=FeeType.fee_by_val, fee_unit=23e-06,
                            slip_type=SlipType.slip_by_point, slip_unit=0.2,
                            limit_change=0.10,
                            exchange='CFFEX',
                            name='上证50股指期货'),

                 'IM': dict(margin_rate=0.08, contract_amt=200.0,
                            fee_type=FeeType.fee_by_val, fee_unit=23e-06,
                            slip_type=SlipType.slip_by_point, slip_unit=0.2,
                            limit_change=0.10,
                            exchange='CFFEX',
                            name='中证1000股指期货'),

                 'TS': dict(margin_rate=0.005, contract_amt=20000.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=3.0,
                            slip_type=SlipType.slip_by_point, slip_unit=0.002,
                            limit_change=0.005,
                            exchange='CFFEX',
                            name='2年期国债期货'),

                 'TF': dict(margin_rate=0.012, contract_amt=10000.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=3.0,
                            slip_type=SlipType.slip_by_point, slip_unit=0.005,
                            limit_change=0.012,
                            exchange='CFFEX',
                            name='5年期国债期货'),

                 'T': dict(margin_rate=0.02, contract_amt=10000.0,
                           fee_type=FeeType.fee_by_amt, fee_unit=3.0,
                           slip_type=SlipType.slip_by_point, slip_unit=0.005,
                           limit_change=0.02,
                           exchange='CFFEX',
                           name='10年期国债期货'),

                 'TL': dict(margin_rate=0.035, contract_amt=10000.0,
                            fee_type=FeeType.fee_by_amt, fee_unit=3.0,
                            slip_type=SlipType.slip_by_point, slip_unit=0.01,
                            limit_change=0.035,
                            exchange='CFFEX',
                            name='30年期国债期货'),
                 }

OPT_UNDERLYING_META = {
    "588000.XSHG": dict(
        contract_multiplier=10000.0,
        underlying_symbol='588000.XSHG',
        name='科创50ETF华夏',
        underlying_type='etf',
        sector='指数ETF',
        fee=1.5,
    ),
    "588080.XSHG": dict(
        contract_multiplier=10000.0,
        underlying_symbol='588080.XSHG',
        name='科创50ETF易方达',
        underlying_type='etf',
        sector='指数ETF',
        fee=1.5,
    ),
    "HO": dict(
        contract_multiplier=100.0,
        underlying_symbol='000016.XSHG',
        name='上证50股指',
        underlying_type='指数',
        sector='指数ETF',
        fee=15.0,
    ),
    "IO": dict(
        contract_multiplier=100.0,
        underlying_symbol='000300.XSHG',
        name='沪深300股指',
        underlying_type='指数',
        sector='指数ETF',
        fee=15.0,
    ),
    "MO": dict(
        contract_multiplier=100.0,
        underlying_symbol='000852.XSHG',
        name='中证1000股指',
        underlying_type='指数',
        sector='指数ETF',
        fee=15.0,
    ),
    "510050.XSHG": dict(
        contract_multiplier=10000.0,
        underlying_symbol='510050.XSHG',
        name='上证50ETF华夏',
        underlying_type='etf',
        sector='指数ETF',
        fee=1.5,
    ),
    "510300.XSHG": dict(
        contract_multiplier=10000.0,
        underlying_symbol='510300.XSHG',
        name='沪深300ETF华泰',
        underlying_type='etf',
        sector='指数ETF',
        fee=1.5,
    ),
    "510500.XSHG": dict(
        contract_multiplier=10000.0,
        underlying_symbol='510500.XSHG',
        name='中证500ETF南方',
        underlying_type='etf',
        sector='指数ETF',
        fee=1.5,
    ),
    "159901.XSHE": dict(
        contract_multiplier=10000.0,
        underlying_symbol='159901.XSHE',
        name='深证100ETF易方达',
        underlying_type='etf',
        sector='指数ETF',
        fee=1.5,
    ),
    "159915.XSHE": dict(
        contract_multiplier=10000.0,
        underlying_symbol='159915.XSHE',
        name='创业板ETF易方达',
        underlying_type='etf',
        sector='指数ETF',
        fee=1.5,
    ),
    "159919.XSHE": dict(
        contract_multiplier=10000.0,
        underlying_symbol='159919.XSHE',
        name='沪深300ETF嘉实',
        underlying_type='etf',
        sector='指数ETF',
        fee=1.5,
    ),
    "159922.XSHE": dict(
        contract_multiplier=10000.0,
        underlying_symbol='159922.XSHE',
        name='中证500ETF嘉实',
        underlying_type='etf',
        sector='指数ETF',
        fee=1.5,
    ),
    "AG": dict(
        contract_multiplier=15.0,
        underlying_symbol='AG',
        name='白银',
        underlying_type='期货',
        sector='贵金属',
        fee=2.0,
    ),
    "AU": dict(
        contract_multiplier=1000.0,
        underlying_symbol='AU',
        name='黄金',
        underlying_type='期货',
        sector='贵金属',
        fee=2.0,
    ),
    "FG": dict(
        contract_multiplier=20.0,
        underlying_symbol='FG',
        name='玻璃',
        underlying_type='期货',
        sector='黑色建材',
        fee=0.5,
    ),
    "I": dict(
        contract_multiplier=100.0,
        underlying_symbol='I',
        name='铁矿石',
        underlying_type='期货',
        sector='黑色建材',
        fee=2.0,
    ),
    "JM": dict(
        contract_multiplier=60.0,
        underlying_symbol='JM',
        name='焦煤',
        underlying_type='期货',
        sector='黑色建材',
        fee=0.5,
    ),
    "RB": dict(
        contract_multiplier=10.0,
        underlying_symbol='RB',
        name='螺纹钢',
        underlying_type='期货',
        sector='黑色建材',
        fee=1.5,
    ),
    "SA": dict(
        contract_multiplier=20.0,
        underlying_symbol='SA',
        name='纯碱',
        underlying_type='期货',
        sector='黑色建材',
        fee=0.5,
    ),
    "SF": dict(
        contract_multiplier=5.0,
        underlying_symbol='SF',
        name='硅铁',
        underlying_type='期货',
        sector='黑色建材',
        fee=0.5,
    ),
    "SM": dict(
        contract_multiplier=5.0,
        underlying_symbol='SM',
        name='锰硅',
        underlying_type='期货',
        sector='黑色建材',
        fee=0.5,
    ),
    "AD": dict(
        contract_multiplier=10.0,
        underlying_symbol='AD',
        name='铸造铝',
        underlying_type='期货',
        sector='有色新能源',
        fee=5.0,
    ),
    "AL": dict(
        contract_multiplier=5.0,
        underlying_symbol='AL',
        name='沪铝',
        underlying_type='期货',
        sector='有色新能源',
        fee=1.5,
    ),
    "AO": dict(
        contract_multiplier=20.0,
        underlying_symbol='AO',
        name='氧化铝',
        underlying_type='期货',
        sector='有色新能源',
        fee=3.5,
    ),
    "CU": dict(
        contract_multiplier=5.0,
        underlying_symbol='CU',
        name='沪铜',
        underlying_type='期货',
        sector='有色新能源',
        fee=5.0,
    ),
    "LC": dict(
        contract_multiplier=1.0,
        underlying_symbol='LC',
        name='碳酸锂',
        underlying_type='期货',
        sector='有色新能源',
        fee=3.0,
    ),
    "NI": dict(
        contract_multiplier=1.0,
        underlying_symbol='NI',
        name='沪镍',
        underlying_type='期货',
        sector='有色新能源',
        fee=1.5,
    ),
    "PB": dict(
        contract_multiplier=5.0,
        underlying_symbol='PB',
        name='沪铅',
        underlying_type='期货',
        sector='有色新能源',
        fee=1.5,
    ),
    "SI": dict(
        contract_multiplier=5.0,
        underlying_symbol='SI',
        name='工业硅',
        underlying_type='期货',
        sector='有色新能源',
        fee=2.0,
    ),
    "SN": dict(
        contract_multiplier=1.0,
        underlying_symbol='SN',
        name='沪锡',
        underlying_type='期货',
        sector='有色新能源',
        fee=1.5,
    ),
    "ZN": dict(
        contract_multiplier=5.0,
        underlying_symbol='ZN',
        name='沪锌',
        underlying_type='期货',
        sector='有色新能源',
        fee=1.5,
    ),
    "BR": dict(
        contract_multiplier=5.0,
        underlying_symbol='BR',
        name='丁二烯橡胶',
        underlying_type='期货',
        sector='能源化工',
        fee=0.5,
    ),
    "BU": dict(
        contract_multiplier=10.0,
        underlying_symbol='BU',
        name='沥青',
        underlying_type='期货',
        sector='能源化工',
        fee=1.0,
    ),
    "BZ": dict(
        contract_multiplier=30.0,
        underlying_symbol='BZ',
        name='纯苯',
        underlying_type='期货',
        sector='能源化工',
        fee=1.0,
    ),
    "EB": dict(
        contract_multiplier=5.0,
        underlying_symbol='EB',
        name='苯乙烯',
        underlying_type='期货',
        sector='能源化工',
        fee=0.5,
    ),
    "EG": dict(
        contract_multiplier=10.0,
        underlying_symbol='EG',
        name='乙二醇',
        underlying_type='期货',
        sector='能源化工',
        fee=0.5,
    ),
    "FU": dict(
        contract_multiplier=10.0,
        underlying_symbol='FU',
        name='燃料油',
        underlying_type='期货',
        sector='能源化工',
        fee=1.0,
    ),
    "L": dict(
        contract_multiplier=5.0,
        underlying_symbol='L',
        name='聚乙烯',
        underlying_type='期货',
        sector='能源化工',
        fee=0.5,
    ),
    "LG": dict(
        contract_multiplier=90.0,
        underlying_symbol='LG',
        name='原木',
        underlying_type='期货',
        sector='其他',
        fee=1.0,
    ),
    "MA": dict(
        contract_multiplier=10.0,
        underlying_symbol='MA',
        name='甲醇',
        underlying_type='期货',
        sector='能源化工',
        fee=0.5,
    ),
    "OP": dict(
        contract_multiplier=40.0,
        underlying_symbol='OP',
        name='胶版纸',
        underlying_type='期货',
        sector='能源化工',
        fee=5.0,
    ),
    "PF": dict(
        contract_multiplier=5.0,
        underlying_symbol='PF',
        name='短纤',
        underlying_type='期货',
        sector='能源化工',
        fee=0.5,
    ),
    "PG": dict(
        contract_multiplier=20.0,
        underlying_symbol='PG',
        name='液化石油气',
        underlying_type='期货',
        sector='能源化工',
        fee=1.0,
    ),
    "PL": dict(
        contract_multiplier=20.0,
        underlying_symbol='PL',
        name='丙烯',
        underlying_type='期货',
        sector='能源化工',
        fee=1.0,
    ),
    "PP": dict(
        contract_multiplier=5.0,
        underlying_symbol='PP',
        name='聚丙烯',
        underlying_type='期货',
        sector='能源化工',
        fee=0.5,
    ),
    "PR": dict(
        contract_multiplier=15.0,
        underlying_symbol='PR',
        name='瓶片',
        underlying_type='期货',
        sector='能源化工',
        fee=1.0,
    ),
    "PS": dict(
        contract_multiplier=3.0,
        underlying_symbol='PS',
        name='多晶硅',
        underlying_type='期货',
        sector='能源化工',
        fee=2.0,
    ),
    "PT": dict(
        contract_multiplier=1000.0,
        underlying_symbol='PT',
        name='铂',
        underlying_type='期货',
        sector='贵金属',
        fee=2.0,
    ),
    "PX": dict(
        contract_multiplier=5.0,
        underlying_symbol='PX',
        name='对二甲苯',
        underlying_type='期货',
        sector='能源化工',
        fee=1.0,
    ),
    "RU": dict(
        contract_multiplier=10.0,
        underlying_symbol='RU',
        name='天然橡胶',
        underlying_type='期货',
        sector='能源化工',
        fee=1.5,
    ),
    "SC": dict(
        contract_multiplier=1000.0,
        underlying_symbol='SC',
        name='原油',
        underlying_type='期货',
        sector='能源化工',
        fee=10.0,
    ),
    "SH": dict(
        contract_multiplier=30.0,
        underlying_symbol='SH',
        name='烧碱',
        underlying_type='期货',
        sector='能源化工',
        fee=2.0,
    ),
    "TA": dict(
        contract_multiplier=5.0,
        underlying_symbol='TA',
        name='PTA',
        underlying_type='期货',
        sector='能源化工',
        fee=0.5,
    ),
    "UR": dict(
        contract_multiplier=20.0,
        underlying_symbol='UR',
        name='尿素',
        underlying_type='期货',
        sector='能源化工',
        fee=1.0,
    ),
    "V": dict(
        contract_multiplier=5.0,
        underlying_symbol='V',
        name='PVC',
        underlying_type='期货',
        sector='能源化工',
        fee=0.5,
    ),
    "A": dict(
        contract_multiplier=10.0,
        underlying_symbol='A',
        name='豆一',
        underlying_type='期货',
        sector='农产品',
        fee=0.5,
    ),
    "AP": dict(
        contract_multiplier=10.0,
        underlying_symbol='AP',
        name='苹果',
        underlying_type='期货',
        sector='农产品',
        fee=1.0,
    ),
    "B": dict(
        contract_multiplier=10.0,
        underlying_symbol='B',
        name='豆二',
        underlying_type='期货',
        sector='农产品',
        fee=0.2,
    ),
    "C": dict(
        contract_multiplier=10.0,
        underlying_symbol='C',
        name='玉米',
        underlying_type='期货',
        sector='农产品',
        fee=0.6,
    ),
    "CF": dict(
        contract_multiplier=5.0,
        underlying_symbol='CF',
        name='棉花',
        underlying_type='期货',
        sector='农产品',
        fee=1.5,
    ),
    "CJ": dict(
        contract_multiplier=5.0,
        underlying_symbol='CJ',
        name='红枣',
        underlying_type='期货',
        sector='农产品',
        fee=1.0,
    ),
    "CS": dict(
        contract_multiplier=10.0,
        underlying_symbol='CS',
        name='玉米淀粉',
        underlying_type='期货',
        sector='农产品',
        fee=0.2,
    ),
    "JD": dict(
        contract_multiplier=10.0,
        underlying_symbol='JD',
        name='鸡蛋',
        underlying_type='期货',
        sector='农产品',
        fee=0.5,
    ),
    "LH": dict(
        contract_multiplier=16.0,
        underlying_symbol='LH',
        name='生猪',
        underlying_type='期货',
        sector='农产品',
        fee=1.5,
    ),
    "M": dict(
        contract_multiplier=10.0,
        underlying_symbol='M',
        name='豆粕',
        underlying_type='期货',
        sector='农产品',
        fee=1.0,
    ),
    "OI": dict(
        contract_multiplier=10.0,
        underlying_symbol='OI',
        name='菜籽油',
        underlying_type='期货',
        sector='农产品',
        fee=1.5,
    ),
    "P": dict(
        contract_multiplier=10.0,
        underlying_symbol='P',
        name='棕榈油',
        underlying_type='期货',
        sector='农产品',
        fee=0.5,
    ),
    "PK": dict(
        contract_multiplier=5.0,
        underlying_symbol='PK',
        name='花生',
        underlying_type='期货',
        sector='农产品',
        fee=0.8,
    ),
    "RM": dict(
        contract_multiplier=10.0,
        underlying_symbol='RM',
        name='菜粕',
        underlying_type='期货',
        sector='农产品',
        fee=0.8,
    ),
    "SR": dict(
        contract_multiplier=10.0,
        underlying_symbol='SR',
        name='白糖',
        underlying_type='期货',
        sector='农产品',
        fee=1.5,
    ),
    "Y": dict(
        contract_multiplier=10.0,
        underlying_symbol='Y',
        name='豆油',
        underlying_type='期货',
        sector='农产品',
        fee=0.5,
    ),
    "PD": dict(
        contract_multiplier=1000.0,
        underlying_symbol='PD',
        name='钯',
        underlying_type='期货',
        sector='贵金属',
        fee=2.0,
    ),
    "SP": dict(
        contract_multiplier=10.0,
        underlying_symbol='SP',
        name='纸浆',
        underlying_type='期货',
        sector='其他',
        fee=1.5,
    ),
}
